name: CI pipeline

on:
  pull_request:
    branches: [main]

jobs:
  execute:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1

      - name: .Net Build
        run: dotnet app.cs
